micronaut:
  application:
    name: api
    hibernate:
      hbm2ddl:
        auto: update
      cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  server:
    port: 8081
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/go_rest`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
jpa:
  default:
      packages-to-scan:
          - 'api.models'
      properties:
          hibernate:
            properties:
              hibernate:
                show_sql: true